# Generated by Django 4.0 on 2021-12-21 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок темы')),
                ('text', models.TextField(verbose_name='Текст темы')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата темы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
