# Generated by Django 4.0 on 2021-12-22 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
            ],
        ),
        migrations.RemoveField(
            model_name='theme',
            name='header',
        ),
        migrations.AddField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публкации'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='theme',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.thread'),
        ),
    ]
